- name: Update the hostname
  copy:
    content: "{{hostname_name}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  when: hostname_name != ""

- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^localhost"
    line: "localhost{{'\t'}}{{hostname_name}}"
    state: present
  when: hostname_name != ""

- name: Run hostname cmd
  hostname:
    name: "{{hostname_name}}"
  when: hostname_name != ""


