# file: timezone/tasks/main.yml

- name: ntp | timezone | Make sure tzdata is installed
  apt:
    pkg: tzdata
    state: present

# TODO: Make this return "OK" or "SKIPPED" if it doesn't need to be done.
- name: ntp | timezone | Update the hardware clock
  command: dpkg-reconfigure -f noninteractive tzdata
